import 'package:astro/Model/review_model.dart';

class ReviewList {
  static List<RatingAndReview> timeList = <RatingAndReview>[
    RatingAndReview(
        rating: 3,
        name: 'Harsh',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
        isReplied: true,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',
    ),
    RatingAndReview(
        rating: 2,
        name: 'Jevin',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 3,
        name: 'Vishal',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 4,
        name: 'Sagar',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: true,
      repliedDate: '17 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thank you so much.',),
    RatingAndReview(
        rating: 4.1,
        name: 'Nadeem',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 3.5,
        name: 'Renish',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 2,
        name: 'Shreyas',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 1,
        name: 'Rugved',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: true,
      repliedDate: '03 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks, god bless you.',),
    RatingAndReview(
        rating: 0,
        name: 'Niyati',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
    RatingAndReview(
        rating: 4.2,
        name: 'Mahima',
        review: 'Thanks for your advice and blessings',
        imageUrl: 'asset/app_logo.png',
      isReplied: false,
      repliedDate: '31 Mar 2022',
      repliedUserName: 'User',
      repliedText: 'Thanks!!!',),
  ];
}
